### ISSUE TITLE
Solicitar cuenta email para la aplicación

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-turnos/planificacion#11]

**Comment by informaticaUNAHUR** [comment]
13/01/2020: en comunicación con DI que está a cargo de la comunicación y señalética para todo el proyecto de aplicación del protocolo y acceso a actividades presenciales, nos informaron que están definiendo un nombre para todo el concepto incluida la App. Se realizará una reunión además con la dirección de Prensa de la universidad la primera semana de febrero y en esa instancia se confirmará nombre y por tanto lo podremos aplicar a la App y a la cuenta de email respectiva.

A nivel de Desarrollo simplemente se podría sacar una cuenta de GMAIL momentánea y usar eso.

dejamos link a la presentación de la carrera de DI: https://docs.google.com/presentation/d/1d2yZN0e3UI1926KKWorFPgMGjmkGNP-lByKygUVg4FQ/edit?usp=sharing

**Comment by faloi** [comment]
Esto puede servir para cuando tengamos que implementar: https://jasonwatmore.com/post/2020/07/20/nodejs-send-emails-via-smtp-with-nodemailer.

**Comment by faloi** [comment]
Vamos a salir con una cuenta @unahur.edu.ar, al menos para probar.

**Comment by informaticaUNAHUR** [comment]
Dado que en demo 19/2 se definió que la aplicación es Turnos UNAHUR , se envió solicitud a Sistemas para crear la cuenta:  turnos@unahur.edu.ar

**Comment by faloi** [comment]
Esto ya está listo. Tenemos además turnos-test para hacer pruebas.
