### ISSUE TITLE
Solicitar listado de trabajadores de UNAHUR

### ISSUE THREAD

**Issue by informaticaUNAHUR** [unahur-turnos/planificacion#20]
Hacer solicitud a Dirección de Personal UNAHUR
Esta lista se utilizará como validador del DNI en el sistema de solicitudes de turnos

**Comment by informaticaUNAHUR** [comment]
11/01/2021 se envía nota a la Directora General de Administración (Marina Ferragut) solicitando la información
archivo: 20210111-SolicitarLISTADOS-2.pdf

se recibe respuesta automática: DGA en vacaciones hasta 01/02

**Comment by faloi** [comment]
Me parece que esto no lo vamos a hacer... ¿Qué opinás @informaticaUNAHUR?

**Comment by informaticaUNAHUR** [comment]
Cerramos porque nunca obtuvimos respuesta y tampoco surgió la necesidad de la funcionalidad
