### ISSUE TITLE
Definir permisos por rol

### ISSUE THREAD

**Issue by faloi** [unahur-turnos/planificacion#51]
Esto va a depender en gran medida de quiénes y cómo vayan a operar el sistema. 

Por ejemplo: ¿lxs bedeles deberían poder editar espacios/actividades? ¿un admin puede pedir autorización para una actividad?

**Comment by JoaquinPettinari** [comment]
Dejo que el admin haga todo, pero que el bedel ni el asistente pueda acceder a lo demas

**Comment by faloi** [comment]
> Dejo que el admin haga todo, pero que el bedel ni el asistente pueda acceder a lo demas

Yo preferiría que el admin solo pueda hacer lo que es del admin. No tiene sentido, con la aplicación como está ahora, que pueda sacar turnos o ver el control de acceso.
